baseurl      = "https://dev-tty.nl"
title        = "My Personal Website"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Embedded Software Architect"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Personal Website"
  keywords = "homepage, blog"
  images = [""]
  [params.portrait]
    path     = "/images/MAATAMsquare.jpg"
    alt      = "Portrait"
    maxWidth = "200px"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/maartentamboer/"

  [[params.social]]
    name = "github"
    url  = "https://github.com/maartentamboer"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/maartentamboer"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Maarten Tamboer"
    subtitle = "Embedded Software Architect"
    keywords = ""
    copyright = 'Maarten Tamboer'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ ls /dev/tty*"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"